version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: service_provider_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: service_provider_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - service_provider_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: service_provider_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - service_provider_network

volumes:
  postgres_data:


networks:
  service_provider_network:
    driver: bridge

